export const API_ROUTER = {
  REGISTER_USER: "user/auth/register-user",
  LOGIN_USER: "user/auth/login",
  // LOGIN_USER: "auth/loginUser",
  FORGET_PASSWORD_USER: "auth/login",
  RESET_PASSWORD_USER: "auth/login",
  CHECK_USERNAME_EXIST: "user/auth/check-username-exist",
  VERIFY_REGISTER_CODE: "user/auth/verify-register-code",
  UPDATE_PROFILE: "user/update",
  FORGOT_PASSWORD: "/user/auth/forgot-password",
  UPDATE_PASSWORD: "/user/auth/update-password",
  VERIFY_FORGET_PASSWORD_CODE: "/user/auth/verify-forgot-code",
  GAME_LIST: "/games",
  SELECT_ROOM: "/room/join-room",
  LEAVE_ROOM: "/room/leave-room",
  GET_AVAILABLE_MATCHES: "/freeplaygame/get-avaliable-matches",
  GET_CURRENT_MATCHES: "/freeplaygame/get-current-matches",
  GET_MY_TOURNAMENT: "/tournament/my-tournament",
  GET_TOURNAMENT_LIST: "/get-tournament-list?consoleId=",
  GET_NEWS: "/news/get-news",
  GET_BADGE: "/get-badges",
  GET_CONSOLE: "/consoles",
  RECENT_EARNERS: "/score/fetch-winner",
  ENTRY_AMOUNT: "/bidamounts",
  GAME_MODE: "/games",
  GAME_MODE_CURRENT_MATCH: "/games/get-current-matches",
  MATCH_REQUEST_CREATE: "/matchrequests/create",
  MATCH_REQUEST_UPDATE_MULTIPLAYER: "/matchrequests/update-multiplayer",
  MATCH_REQUEST_UPDATE: "/matchrequests/update",
  GAME_RULE: "/rulesbygame/",
  UPDATE_MATCH_STATUS: "/matchrequests/update-start-match-status",
  UPDATE_READY_STATUS: "/matchrequests/update-ready-status",
  UPDATE_READY_TOURNAMENT_STATUS: "/tournament/update-ready-status",
  TOURNAMENT_MATCH_RESULT: "/tournament/match-result",
  TOURNAMENT_SUBMIT_SCORE: "/tournamentscore/add-score",

  MATCH_RESULT: "/matchrequests/match-result",
  SUBMIT_SCORE: "/score/add-score",
  AVAILABLE_MATCH_JOIN: "/matchrequests/do-match-from-avaliable",
  FREE_PLAY_AVAILABLE_MATCH_JOIN: "/freeplaymatch/do-match-from-avaliable",
  WITHDRAW_AMOUNT: "/payment/add-paypal-data",
  PAYPAL_PLAN_DETAIL: "/payment/paypal-plan-details",
  GET_SUBSCRIPTION_DETAIL: "/user/user-subscription-details",
  PAYPAL_SUBSCRIPTION_ADD: "/payment/paypal-subscription",
  TOURNAMENT_REGISTER: "/tournament-register",
  GET_CURRENT_TOURNAMENT_MATCH: "/tournament/get-current-match?",
  REGISTER_USER_LIST: "/get-registerd-tour-user-list",

  //Chat
  ROOM_CHAT: "/room/groupchat/message-list?",
  SEND_ROOM_CHAT: "/room/groupchat/send-message-topic",
  SEND_CHAT: "/chat/create-chat",
  SEND_DISPUTE_CHAT: "/disputeschat/create-disputes-chat",
  UPDATE_START_MATCH: "/tournament/update-start-match-status",

  //
  DISPUTES_LIST: "/disputes",
  MATCH_HISTORY: "/games/get-completed-game",
  GET_PROFILE_CARD: "/user/get-user-profile-card?",
  GET_SEASON_LIST: "/get-season-list",
  CREATE_DISPUTES: "/disputes/create",
  GET_GAME_REMAIN: "/games/get-remain-disputes-game",
  USER_SEARCH_BADGE: "/user-search-badges",

  GET_GAME_WIN_LOSS: "/user/game-with-winloss?",
  GET_BADGES: "/get-user-badges",
  GetGameWithWinLoss: "/user/game-with-winloss?",
  GET_GAME_HISTORY: "/games/get-game-list",
  GET_BADGE_LIST: "/get-badgelevel-list",
  ROOM_CHAT_THREAD: "/room/groupchat/get-roomchat-thread",
  USER_CHAT_LIST: "/chat/user-chat-list",
  CHAT_LIST: "/chat/chatlist",
  GET_PROFILE: "/user/",
  GET_DISPUTE_CHAT: "/disputeschat/get-disputes-chat",
  GET_USER_SEARCH: "/user/get-search-user",
  GAME_LIST: "/games?",
  GAME_BY_CONSOLE: "/gamesbyconsole/",
  UPDATE_PROFILE: "/user/update",
  PAYPAL_PLAN_LIST: "/payment/paypal-charges-details",
  CARD_PURCHASE: "/payment/card-purchase-new",
  TOURNAMENT_RULES: "/get-tournament-rules-list/",
  TOP_5_USER: "/games/get-top5-win-user",
  ADD_DEVICE_TOKEN: "/user/change-device-token-and-type",
  TEST_NOTIFICATION: "/test-notification",
  NOTIFICATION_LIST: "/notification/get-notification",
  GET_USER_POINT: "/user/get-user-points",
  GET_BADGE_USER_LIST: "/get-earn-badges-user-list",
  DELETE_MATCH: "/matchrequests/delete-match",
  FP_DELETE_MATCH: "/freeplaymatch/delete-match",
  challengeFriendApi: "/matchrequests/add-match-challenges",
  FpchallengeFriendApi: "freeplaymatch/add-match-challenges",
  //

  FREE_PLAY_MATCH_REQUEST_CREATE: "/freeplaymatch/create",
  FREE_PLAY_MATCH_REQUEST_UPDATE: "/freeplaymatch/update",
  FREE_PLAY_UPDATE_MATCH_STATUS: "/freeplaymatch/update-start-match-status",
  FREE_PLAY_UPDATE_READY_STATUS: "/freeplaymatch/update-ready-status",
  FREE_PLAY_MATCH_RESULT: "/freeplaymatch/match-result",
  FREE_PLAY_SUBMIT_SCORE: "/freeplayscore/add-score",
};
